### ISSUE TITLE
Support of the Privacy API for GDPR

### ISSUE THREAD

**Issue by tholudwig** [serlo/moodle-mod_serlo#1]
Moodle offers a complete API to fulfil the requirements of the EU GDPR.

This includes a number of components, among others these include a user's right to:

- request information on the types of personal data held, the instances of that data, and the deletion policy for each;
- access all of their data; and
- be forgotten.

To fulfil these requirements, the plugin should support the API. You can find out more at: https://moodledev.io/docs/4.4/apis/subsystems/privacy

**Comment by kulla** [comment]
Thank you @tholudwig for the link to https://moodledev.io/docs/4.4/apis/subsystems/privacy and all the other issues you have reported. Those information are very helpful :heart:
